version: '3.3'

services:
  dev-main-db:
    image: postgres:10
    hostname: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distributionnetworkdb
    ports:
      - "5432:5432"
    volumes:
    - ./initdb/:/docker-entrypoint-initdb.d/
