version: '3.3'

services:
  postgresdb:
    image: postgres:9.5.25-alpine
    hostname: postgresdb
    restart: always
#    network_mode: host
    networks:
      - pr
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distributionnetworkdb
    ports:
      - "5432:5432"
    volumes:
    - ./initdb/:/docker-entrypoint-initdb.d/

networks:
  pr:
    driver: bridge
