version: "3.4"

services:
  grafana:
    image: 127.0.0.1:5001/grafana
    build: ./grafana_src
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    environment:
      GF_SECURITY_ADMIN_USER: iasset
      GF_SECURITY_ADMIN_PASSWORD: iasset
#      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      DATABASE: "cz.icecars.iot4cps-wp5-CarFleet.Car1"
      # "[cz.icecars.iot4cps-wp5-CarFleet.Car1-]YYYY.MM"
      # "[at.datahouse.Analytics.RoadAnalytics-]YYYY.MM"
#    volumes:
#      - ./grafanadata:/var/lib/grafana

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    env_file:
      - .env
    environment:
      - bla=12
    volumes:
      - ./influxdata:/var/lib/influxdb

networks:
  monitoring:
    driver: bridge

#volumes:
#  grafana-volume:
#    external: true
#  influxdb-volume:
#    external: true