version: "3.4"

services:
  grafana:
    image: 127.0.0.1:5001/grafana
    build: ./grafana_src
    container_name: ${SYSTEM_NAME}_grafana
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - monitoring
    env_file:
      - .env
    depends_on:
      - influxdb
#    volumes:
#      - ./grafanadata:/var/lib/grafana

  influxdb:
    image: influxdb:1.8.3
    container_name: ${SYSTEM_NAME}_influxdb
    restart: always
    ports:
      - "${INFLUXDB_PORT}:8086"
    networks:
      - monitoring
    env_file:
      - .env
    volumes:
      - ./influxdata:/var/lib/influxdb

networks:
  monitoring:
    driver: bridge
