version: "3.4"

services:
  datastore-adapter:
    image: 127.0.0.1:5001/datastore-adapter
    build: ./influxdb-adapter
    container_name: datastore-adapter
    network_mode: host
    environment:
      VERBOSE: "true"
      # InfluxDB configuration
      INFLUXDB_HOST: "localhost"
      # Panta Rhei configuration
      CLIENT_NAME: "analytic"
      SYSTEM_NAME: "cz.icecars.iot4cps-wp5-CarFleet.Car1"
      SERVER_URI: "localhost:1908"
      KAFKA_BOOTSTRAP_SERVERS: ":9092"
      # "192.168.48.71:9092,192.168.48.71:9093,192.168.48.71:9094"
    restart: always

  grafana:
    image: 127.0.0.1:5001/grafana
    build: ./InfluxDB_Grafana/grafana_src
    container_name: grafana
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - monitoring
    env_file:
      - InfluxDB_Grafana/.env
    depends_on:
      - influxdb
#    volumes:
#      - ./InfluxDB_Grafana/grafanadata:/var/lib/grafana

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    ports:
      - ${INFLUXDB_PORT}:8086
    networks:
      - monitoring
    env_file:
      - ./InfluxDB_Grafana/.env
    environment:
      - bla=12
    volumes:
      - ./InfluxDB_Grafana/influxdata:/var/lib/influxdb



networks:
  monitoring:
    driver: bridge
